"""initial

Revision ID: 90943beca35f
Revises: 
Create Date: 2026-05-05 00:58:43.243299
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '90943beca35f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_performance',
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('total_tasks', sa.Integer(), server_default='0', nullable=True),
    sa.Column('success_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('avg_execution_time_ms', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('agent_name')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), server_default='', nullable=True),
    sa.Column('system_prompt', sa.Text(), server_default='', nullable=False),
    sa.Column('craft_declaration', sa.Text(), nullable=True),
    sa.Column('tools', sa.Text(), server_default='[]', nullable=True),
    sa.Column('skill_ids', sa.Text(), server_default='[]', nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=True),
    sa.Column('version', sa.Text(), server_default='1.0.0', nullable=True),
    sa.Column('created_by', sa.Text(), server_default='', nullable=True),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_used_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Text(), nullable=False),
    sa.Column('contract_type', sa.Text(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), server_default='1.0.0', nullable=True),
    sa.Column('status', sa.Text(), server_default='draft', nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id')
    )
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), server_default='default', nullable=False),
    sa.Column('title', sa.Text(), server_default='新对话', nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('daily_budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('budget_usd', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('spent_usd', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('alert_sent', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('execution_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=False),
    sa.Column('parent_log_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('level', sa.Text(), server_default='INFO', nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), server_default='{}', nullable=True),
    sa.Column('project_id', sa.Text(), server_default='', nullable=True),
    sa.Column('duration_ms', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['parent_log_id'], ['execution_logs.log_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('instinct_patterns',
    sa.Column('pattern_id', sa.Text(), nullable=False),
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.Column('task_signature', sa.Text(), nullable=False),
    sa.Column('topology_json', sa.Text(), nullable=False),
    sa.Column('success_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('confidence', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('is_active', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('pattern_id')
    )
    op.create_table('kb_project_assignments',
    sa.Column('kb_name', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('kb_name', 'project_id')
    )
    op.create_table('keyword_features',
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('last_used', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('keyword', 'agent_name')
    )
    op.create_table('knowledge_bases',
    sa.Column('kb_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=True),
    sa.Column('document_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('kb_name')
    )
    op.create_table('llm_providers',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('auth_type', sa.Text(), server_default='OpenAI', nullable=False),
    sa.Column('api_url', sa.Text(), server_default='', nullable=False),
    sa.Column('api_key', sa.Text(), server_default='', nullable=False),
    sa.Column('model', sa.Text(), server_default='', nullable=False),
    sa.Column('api_version', sa.Text(), server_default='', nullable=False),
    sa.Column('max_tokens', sa.Integer(), server_default='4096', nullable=False),
    sa.Column('temperature', sa.Float(), server_default='0.7', nullable=False),
    sa.Column('timeout', sa.Integer(), server_default='120', nullable=False),
    sa.Column('is_active', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_entries',
    sa.Column('memory_id', sa.Text(), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('scope_id', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), server_default='{}', nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('last_accessed_at', sa.Text(), nullable=False),
    sa.Column('access_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('retention', sa.Float(), server_default='1.0', nullable=True),
    sa.Column('is_archived', sa.Integer(), server_default='0', nullable=True),
    sa.Column('is_important', sa.Integer(), server_default='0', nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_table('orchestration_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), server_default='bi-diagram-3', nullable=True),
    sa.Column('color', sa.Text(), server_default='#4361ee', nullable=True),
    sa.Column('workflow_type', sa.Text(), nullable=False),
    sa.Column('default_phases_json', sa.Text(), nullable=True),
    sa.Column('flow_rules_json', sa.Text(), nullable=True),
    sa.Column('suitable_for_json', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('created_by', sa.Text(), server_default='', nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('report_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('report_type', sa.Text(), nullable=False),
    sa.Column('delivery_method', sa.Text(), server_default='email', nullable=True),
    sa.Column('delivery_config_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=True),
    sa.Column('subscribed_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('unsubscribed_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'report_type')
    )
    op.create_table('routing_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Text(), nullable=True),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('task_hash', sa.Text(), nullable=True),
    sa.Column('selected_agent', sa.Text(), nullable=True),
    sa.Column('routing_strategy', sa.Text(), server_default='keyword', nullable=True),
    sa.Column('status', sa.Text(), server_default='success', nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), server_default='', nullable=False),
    sa.Column('value_type', sa.Text(), server_default='str', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=True),
    sa.Column('category', sa.Text(), server_default='general', nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('skill_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('tag', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'tag')
    )
    op.create_table('skill_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('argument_hint', sa.Text(), nullable=True),
    sa.Column('allowed_tools', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('maintainer_agent', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_used_at', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id')
    )
    op.create_table('squad_agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('squad_id', sa.Text(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=True),
    sa.Column('is_lead', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('weight', sa.Float(), server_default='1.0', nullable=True),
    sa.Column('conditions_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('squad_id', 'phase', 'agent_name')
    )
    op.create_table('squad_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Text(), nullable=False),
    sa.Column('squad_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=True),
    sa.Column('current_phase', sa.Integer(), server_default='1', nullable=True),
    sa.Column('progress_percent', sa.Float(), server_default='0', nullable=True),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('estimated_completion_at', sa.Text(), nullable=True),
    sa.Column('actual_duration_hours', sa.Float(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('outputs_json', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details_json', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id')
    )
    op.create_table('squad_phase_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Text(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('phase_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=True),
    sa.Column('primary_agent', sa.Text(), nullable=False),
    sa.Column('supporting_agents_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('outputs_json', sa.Text(), nullable=True),
    sa.Column('success_criteria_met_json', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', 'phase')
    )
    op.create_table('squad_workflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('squad_id', sa.Text(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mode', sa.Text(), server_default='sequential', nullable=True),
    sa.Column('parent_phase', sa.Integer(), nullable=True),
    sa.Column('conditions_json', sa.Text(), nullable=True),
    sa.Column('consensus_threshold', sa.Float(), server_default='0.5', nullable=True),
    sa.Column('estimated_duration_hours', sa.Integer(), server_default='24', nullable=True),
    sa.Column('max_duration_hours', sa.Integer(), server_default='48', nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('squad_id', 'phase')
    )
    op.create_table('squads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('squad_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Text(), server_default='1.0.0', nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('workflow_type', sa.Text(), server_default='sequential', nullable=True),
    sa.Column('max_parallel_agents', sa.Integer(), server_default='1', nullable=True),
    sa.Column('estimated_duration_days', sa.Integer(), server_default='7', nullable=True),
    sa.Column('quality_gates_json', sa.Text(), nullable=True),
    sa.Column('success_metrics_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('parent_squad_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_executed_at', sa.Text(), nullable=True),
    sa.Column('execution_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('success_count', sa.Integer(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('squad_id')
    )
    op.create_table('strategy_performance',
    sa.Column('strategy_name', sa.Text(), nullable=False),
    sa.Column('total_decisions', sa.Integer(), server_default='0', nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('avg_execution_time_ms', sa.Float(), nullable=True),
    sa.Column('feedback_correct_rate', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), server_default='1.0', nullable=True),
    sa.PrimaryKeyConstraint('strategy_name')
    )
    op.create_table('token_budget',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('daily_budget', sa.Float(), server_default='10.0', nullable=True),
    sa.Column('daily_budget_usd', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('monthly_budget', sa.Float(), server_default='300.0', nullable=True),
    sa.Column('monthly_budget_usd', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('alert_threshold', sa.Float(), server_default='0.8', nullable=True),
    sa.Column('alert_email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=True),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=True),
    sa.Column('cost_usd', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topology_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_signature', sa.Text(), nullable=False),
    sa.Column('topology', sa.Text(), nullable=False),
    sa.Column('satisfaction', sa.Float(), nullable=False),
    sa.Column('execution_id', sa.Text(), server_default='', nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Text(), nullable=False),
    sa.Column('report_type', sa.Text(), server_default='weekly', nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('total_executions', sa.Integer(), server_default='0', nullable=True),
    sa.Column('successful_executions', sa.Integer(), server_default='0', nullable=True),
    sa.Column('failed_executions', sa.Integer(), server_default='0', nullable=True),
    sa.Column('avg_duration_hours', sa.Float(), server_default='0', nullable=True),
    sa.Column('active_squads', sa.Integer(), server_default='0', nullable=True),
    sa.Column('most_used_squad', sa.Text(), nullable=True),
    sa.Column('most_successful_squad', sa.Text(), nullable=True),
    sa.Column('top_performing_agents_json', sa.Text(), nullable=True),
    sa.Column('most_used_agents_json', sa.Text(), nullable=True),
    sa.Column('routing_decisions_total', sa.Integer(), server_default='0', nullable=True),
    sa.Column('routing_success_rate', sa.Float(), server_default='0', nullable=True),
    sa.Column('top_routing_strategies_json', sa.Text(), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_cost_usd', sa.Float(), server_default='0', nullable=True),
    sa.Column('cost_by_agent_json', sa.Text(), nullable=True),
    sa.Column('cost_by_model_json', sa.Text(), nullable=True),
    sa.Column('total_skills_used', sa.Integer(), server_default='0', nullable=True),
    sa.Column('most_used_skills_json', sa.Text(), nullable=True),
    sa.Column('skill_usage_trend_json', sa.Text(), nullable=True),
    sa.Column('contracts_created', sa.Integer(), server_default='0', nullable=True),
    sa.Column('contracts_approved', sa.Integer(), server_default='0', nullable=True),
    sa.Column('contract_types_distribution_json', sa.Text(), nullable=True),
    sa.Column('performance_trend_json', sa.Text(), nullable=True),
    sa.Column('improvement_areas_json', sa.Text(), nullable=True),
    sa.Column('recommendations_json', sa.Text(), nullable=True),
    sa.Column('summary_markdown', sa.Text(), nullable=True),
    sa.Column('detailed_analysis_json', sa.Text(), nullable=True),
    sa.Column('charts_config_json', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.Text(), server_default='system', nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('published_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('candidate_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('rank', sa.Integer(), server_default='0', nullable=True),
    sa.Column('features_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['routing_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Text(), nullable=False),
    sa.Column('depends_on_contract_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'depends_on_contract_id')
    )
    op.create_table('contract_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Text(), nullable=False),
    sa.Column('tag', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'tag')
    )
    op.create_table('contract_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_agents',
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('task_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'agent_name')
    )
    op.create_table('kb_documents',
    sa.Column('doc_id', sa.Text(), nullable=False),
    sa.Column('kb_name', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('char_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('text_content', sa.Text(), server_default='', nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kb_name'], ['knowledge_bases.kb_name'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Text(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), server_default='{}', nullable=True),
    sa.Column('status', sa.Text(), server_default='completed', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('trace_id', sa.Text(), server_default='', nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.message_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.Text(), server_default='correct', nullable=True),
    sa.Column('corrected_agent', sa.Text(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['routing_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_feedback')
    op.drop_table('messages')
    op.drop_table('kb_documents')
    op.drop_table('conversation_agents')
    op.drop_table('contract_versions')
    op.drop_table('contract_tags')
    op.drop_table('contract_dependencies')
    op.drop_table('candidate_scores')
    op.drop_table('weekly_reports')
    op.drop_table('topology_feedback')
    op.drop_table('token_usage')
    op.drop_table('token_budget')
    op.drop_table('strategy_performance')
    op.drop_table('squads')
    op.drop_table('squad_workflows')
    op.drop_table('squad_phase_executions')
    op.drop_table('squad_executions')
    op.drop_table('squad_agents')
    op.drop_table('skills')
    op.drop_table('skill_usage')
    op.drop_table('skill_tags')
    op.drop_table('settings')
    op.drop_table('routing_decisions')
    op.drop_table('report_subscriptions')
    op.drop_table('projects')
    op.drop_table('orchestration_patterns')
    op.drop_table('memory_entries')
    op.drop_table('llm_providers')
    op.drop_table('knowledge_bases')
    op.drop_table('keyword_features')
    op.drop_table('kb_project_assignments')
    op.drop_table('instinct_patterns')
    op.drop_table('execution_logs')
    op.drop_table('daily_budgets')
    op.drop_table('conversations')
    op.drop_table('contracts')
    op.drop_table('agents')
    op.drop_table('agent_performance')
    # ### end Alembic commands ###
